apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-backend
  labels:
    {{- include "todo-app.backend.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "todo-app.backend.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
    nodePort: {{ .Values.backend.service.nodePort }}
