{{- if .Values.secrets.managed }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.secretName" . }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | default "" | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.betterAuthSecret | default "" | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | default "" | quote }}
{{- end }}
